Tutorial/Tutorial/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from Tutorial import views as tutorial_views
from rest_framework import routers
from quickstart import views
from rest_framework.urlpatterns import format_suffix_patterns

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)
router.register(r'userprofile', views.UserProfileViewSet)

urlformatpatterns = [
#     path('snippets/', views.snippet_list),
#     path('snippets/<int:pk>/', views.snippet_detail),
    path('snippets/', views.SnippetList.as_view()),
    path('snippets/<int:pk>/', views.SnippetDetail.as_view()),
    path('users/', views.UserList.as_view()),
    path('users/<int:pk>/', views.UserDetail.as_view()),
]

urlformatpatterns = format_suffix_patterns(urlformatpatterns)

urlpatterns = [
    #path('',tutorial_views.login_redirect, name = 'login_redirect'),
	path('',tutorial_views.web_home, name = 'web_home'),
    path('admin/', admin.site.urls),
    path('drf/', include(router.urls)),
    path('account/', include(('accounts.urls', 'accounts'), namespace = 'accounts')),
    path('home/', include(('home.urls', 'home'), namespace = 'home')),
    path('paytm/', include(('paytm.urls', 'paytm'), namespace = 'paytm')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + urlformatpatterns

Tutorial/accounts/urls.py
from django.urls import path, re_path, reverse_lazy
from accounts import views
from django.contrib.auth import views as auth_views

# app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('profile/', views.view_profile, name='view_profile'),
    re_path(r'profile/(?P<pk>\d+)/', views.view_profile, name='view_profile_with_pk'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('profile/password/', views.change_password, name='change_password'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
    path('reset-password/', auth_views.PasswordResetView.as_view(template_name='accounts/reset_password.html', email_template_name='accounts/reset_password_email.html', success_url=reverse_lazy('accounts:password_reset_done')), name='reset_password'),
    path('reset-password/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/reset_password_done.html'), name='password_reset_done'),
    re_path(r'reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/', auth_views.PasswordResetConfirmView.as_view(template_name='accounts/reset_password_confirm.html', success_url=reverse_lazy('accounts:password_reset_complete')), name='password_reset_confirm'),
    path('reset-password/complete/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/reset_password_complete.html'), name='password_reset_complete'),
#     path('payment/', views.payment, name='payment'),
]

Tutorial/home/urls.py
from django.urls import path, re_path
from home import views

# app_name = 'home'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    re_path(r'friend/(?P<operation>.+)/(?P<pk>\d+)/', views.change_friends, name='change_friend')
]

Tutorial/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save

# Create your models here.
class UserProfileManager(models.Manager):
    
    def get_queryset(self):
        return super(UserProfileManager, self).get_queryset()#.filter(city__endswith='Bangalore')

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    description = models.CharField(max_length = 100, default = '')
    city = models.CharField(max_length = 100, default = '')
    website = models.URLField(default = '')
    phone = models.BigIntegerField(default = 0)
    image = models.ImageField(upload_to='profile_images', default='empty_avatar.jpg')
    
    bangalore = UserProfileManager()
    objects = models.Manager()
    
    def __str__(self):
        return self.user.username
    
def create_profile(sender, **kwargs):
    if kwargs['created']:
        UserProfile.objects.create(user=kwargs['instance'])
        
post_save.connect(create_profile, sender=User)

Tutorial/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    
    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2'
        ]
        
    def save(self, commit=True):
        user = super(RegistrationForm, self).save(commit=False)
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        user.email = self.cleaned_data['email']
        
        if commit:
            user.save()
            
        return user

class EditProfileForm(UserChangeForm):
    
    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
            'email',
            'password',
        ]

Tutorial/accounts/views.py
from django.shortcuts import render, redirect, reverse
from accounts.forms import RegistrationForm, EditProfileForm
from django.contrib.auth import update_session_auth_hash, authenticate, login
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth.models import User
from django.contrib import messages
from django.conf import settings

# Create your views here.

def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            username = request.POST.get('username')
            password = request.POST.get('password1')
            user = authenticate(request, username=username, password=password)
            login(request, user)
            return redirect(reverse('home:home'))
    else:
        form = RegistrationForm()
        
    args = {'form': form}
    return render(request, 'accounts/register.html', args)

def view_profile(request, pk = None):
    storage = messages.get_messages(request)
    if pk:
        user = User.objects.get(pk=pk)
    else:
        user = request.user
    args = {'user': user, 'messages': storage}
    return render(request, 'accounts/profile.html', args)

def edit_profile(request):
    if request.method == 'POST':
        form = EditProfileForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect(reverse('accounts:view_profile'))
    else:
        form = EditProfileForm(instance = request.user)
        
        args = {'form': form}
        return render(request, 'accounts/edit_profile.html', args)
    
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your password has been changed successfully.')
            update_session_auth_hash(request, form.user)
            return redirect(reverse('accounts:view_profile'))
    else:
        form = PasswordChangeForm(user = request.user)
        
    args = {'form': form}
    return render(request, 'accounts/change_password.html', args)

Tutorial/accounts/templates/accounts/change_password.html
{% extends 'base.html' %}

{% block head %}
	<title>Edit Profile</title>
{% endblock %}

{% block body %}
	<div class="container">
		<h1>Password Change</h1>
		<form method="POST">
			{% csrf_token %}
			{{ form.as_p }}
			<button type="submit" class="btn btn-info">Submit</button>
		</form>
	</div>
	<br>
{% endblock %}

Tutorial/accounts/templates/accounts/edit_profile.html
{% extends 'base.html' %}

{% block head %}
	<title>Edit Profile</title>
{% endblock %}

{% block body %}
	<div class="container">
		<h1>Edit Profile</h1>
		<form method="POST">
			{% csrf_token %}
			{{ form.as_p }}
			<button type="submit" class="btn btn-info">Submit</button>
		</form>
	</div>
	<br>
{% endblock %}

Tutorial/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block head %}
	<title>Login</title>
{% endblock %}

{% block body %}
	<div class="container">
		<h1>Welcome</h1>
		<p>You can log in here!</p>
		<h2>Login</h2>
		<form method="post">
			{% csrf_token %}
			{{ form.as_p }}
			<button type="submit" class="btn btn-info">Login</button>
		</form>
	</div>
{% endblock %}

Tutorial/accounts/templates/accounts/logout.html
{% extends 'base.html' %}

{% block head %}
	<title>Logout</title>
{% endblock %}

{% block body %}
	<div class="container">
		<h1>Logged Out</h1>
		<p>You have logged out!</p>
		<p>Click <a href="{% url 'accounts:login' %}">here</a> to login again</p>
	</div>
{% endblock %}

Tutorial/accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block head %}
	<title>Profile</title>
{% endblock %}

{% block body %}
	<div class="container">
		<div class="col-xs-12">
			{% if messages %}
				{% for message in messages %}
					<div class="" role="alert">
						<center>{{ message }}</center>
					</div>
				{% endfor %}
			{% endif %}
		<h1>Profile</h1>
		<p>Username: {{ user }}</p>
		<p>First Name: {{ user.first_name }}</p>
		<p>Last Name: {{ user.last_name }}</p>
		<p>Email: {{ user.email }}</p>
		<p>Description: {{ user.userprofile.description }}</p>
		<p>City: {{ user.userprofile.city }}</p>
		<p>Phone: {{ user.userprofile.phone }}</p>
		<p>Website: <a href="{{ user.userprofile.website }}">{{ user.userprofile.website }}</a></p>
		{% if user.userprofile.image %}
			<img src="{{ user.userprofile.image.url }}" width="150" height="150">
		{% endif %}		
	</div>
{% endblock %}

Tutorial/accounts/templates/accounts/register.html
{% extends 'base.html' %}

{% block head %}
	<title>Register</title>
{% endblock %}

{% block body %}
	<div class="container">
		<h1>Register</h1>
		<form method="post">
			{% csrf_token %}
			{{ form.as_p }}
			<button type="submit" class="btn btn-info">Register</button>
		</form>
	</div>
{% endblock %}

Tutorial/accounts/templates/accounts/reset_password.html
{% extends 'base.html' %}

{% block head %}
	<title>Reset Password</title>
{% endblock %}

{% block body %}
	<div class="container">
		<h1>Password Reset</h1>
		<p>
			Forgotten your password? Enter your email address below, and we'll email instructions for setting a new one.
		</p>
		<form method="post">
			{% csrf_token %}
			{{ form.as_p }}
			<button type="submit" class="btn btn-info">Reset Password</button>
		</form>
	</div>
{% endblock %}

Tutorial/accounts/templates/accounts/reset_password_complete.html
{% extends 'base.html' %}

{% block head %}
	<title>Reset Password</title>
{% endblock %}

{% block body %}
	<div class="container">
		<h1>Password Reset Complete</h1>
		<p>
			Password changed successfully.
		</p>
		<a class="btn btn-info" href="{% url 'accounts:login' %}">Log In</a>
	</div>
{% endblock %}

Tutorial/accounts/templates/accounts/reset_password_confirm.html
{% extends 'base.html' %}

{% block head %}
	<title>Reset Password</title>
{% endblock %}

{% block body %}
	<div class="container">
		<h1>Enter new password</h1>
		<form method="post">
			{% csrf_token %}
			{{ form.as_p }}
			<button type="submit" class="btn btn-info">Reset Password</button>
		</form>
	</div>
{% endblock %}

Tutorial/accounts/templates/accounts/reset_password_done.html
{% extends 'base.html' %}

{% block head %}
	<title>Email Sent</title>
{% endblock %}

{% block body %}
	<div class="container">
		<h1>Password Reset Sent</h1>
		<p>
			We've emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.
		</p>
		<p>
			If you don't receive an email, please make sure you've entered the address you registered with, and check your spam folder.
		</p>
	</div>
{% endblock %}

Tutorial/accounts/templates/accounts/reset_password_email.html
{% load i18n %}{% autoescape off %}
{% blocktrans %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktrans %}

{% trans "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% trans "Your username, in case you've forgotten:" %} {{ user.get_username }}

{% trans "Thanks for using our site!" %}

{% blocktrans %}The {{ site_name }} team{% endblocktrans %}

{% endautoescape %}