Tutorial/Tutorial/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from Tutorial import views as tutorial_views
from rest_framework import routers
from quickstart import views
from rest_framework.urlpatterns import format_suffix_patterns

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)
router.register(r'userprofile', views.UserProfileViewSet)

urlformatpatterns = [
#     path('snippets/', views.snippet_list),
#     path('snippets/<int:pk>/', views.snippet_detail),
    path('snippets/', views.SnippetList.as_view()),
    path('snippets/<int:pk>/', views.SnippetDetail.as_view()),
    path('users/', views.UserList.as_view()),
    path('users/<int:pk>/', views.UserDetail.as_view()),
]

urlformatpatterns = format_suffix_patterns(urlformatpatterns)

urlpatterns = [
    #path('',tutorial_views.login_redirect, name = 'login_redirect'),
	path('',tutorial_views.web_home, name = 'web_home'),
    path('admin/', admin.site.urls),
    path('drf/', include(router.urls)),
    path('account/', include(('accounts.urls', 'accounts'), namespace = 'accounts')),
    path('home/', include(('home.urls', 'home'), namespace = 'home')),
    path('paytm/', include(('paytm.urls', 'paytm'), namespace = 'paytm')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + urlformatpatterns

Tutorial/accounts/urls.py
from django.urls import path, re_path, reverse_lazy
from accounts import views
from django.contrib.auth import views as auth_views

# app_name = 'accounts'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('profile/', views.view_profile, name='view_profile'),
    re_path(r'profile/(?P<pk>\d+)/', views.view_profile, name='view_profile_with_pk'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('profile/password/', views.change_password, name='change_password'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
    path('reset-password/', auth_views.PasswordResetView.as_view(template_name='accounts/reset_password.html', email_template_name='accounts/reset_password_email.html', success_url=reverse_lazy('accounts:password_reset_done')), name='reset_password'),
    path('reset-password/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/reset_password_done.html'), name='password_reset_done'),
    re_path(r'reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/', auth_views.PasswordResetConfirmView.as_view(template_name='accounts/reset_password_confirm.html', success_url=reverse_lazy('accounts:password_reset_complete')), name='password_reset_confirm'),
    path('reset-password/complete/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/reset_password_complete.html'), name='password_reset_complete'),
#     path('payment/', views.payment, name='payment'),
]

Tutorial/home/urls.py
from django.urls import path, re_path
from home import views

# app_name = 'home'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    re_path(r'friend/(?P<operation>.+)/(?P<pk>\d+)/', views.change_friends, name='change_friend')
]

Tutorial/home/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    post = models.CharField(max_length=500)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    
class Friend(models.Model):
    users = models.ManyToManyField(User)
    current_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='owner', null=True)
    
    def __str__(self):
        return self.current_user.first_name.lower() + ' friends'
    
    @classmethod
    def make_friend(cls, current_user, new_friend):
        friend, created = cls.objects.get_or_create(current_user=current_user)
        friend.users.add(new_friend)
        
    @classmethod
    def lose_friend(cls, current_user, new_friend):
        friend, created = cls.objects.get_or_create(current_user=current_user)
        friend.users.remove(new_friend)

Tutorial/home/forms.py
from django import forms
from home.models import Post

class HomeForm(forms.ModelForm):
    post = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Write a post...'
            }
        )
    )
    
    class Meta:
        model = Post
        fields = ('post',)

Tutorial/home/views.py
from django.views.generic import TemplateView
from django.shortcuts import render, redirect
from django.contrib.auth.models import User

from home.forms import HomeForm
from home.models import Post, Friend

import logging

class HomeView(TemplateView):
    template_name = 'home/home.html'
    
    def get(self, request):
        form = HomeForm()
        posts = Post.objects.all().order_by('-created')
        users = User.objects.exclude(id=request.user.id)
        
        friend, created = Friend.objects.get_or_create(current_user=request.user)
        friends = friend.users.all()
            
        args = {'form': form, 'posts': posts, 'users': users, 'friends': friends}
        return render(request, self.template_name, args)
    
    def post(self, request):
        form = HomeForm(request.POST)
        
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            
            text = form.cleaned_data['post']
            form = HomeForm()
            return redirect('home:home')
            
        args = {'form': form, 'text': text}
        return render(request, self.template_name, args)
    
def change_friends(request, operation, pk):
    friend = User.objects.get(pk=pk)
    if operation == 'add':
        Friend.make_friend(request.user, friend)
    elif operation == 'remove':
        Friend.lose_friend(request.user, friend)
        
    return redirect('home:home')

Tutorial/home/templates/home/home.html
{% extends 'base.html' %}

{% block head %}
	<title>Home</title>
{% endblock %}

{% block body %}
	<div class="container">
		<div class="col-md-7">
			<h2>HomePage</h2>
			<form method="post">
				{% csrf_token %}
				{{ form.post }}
				<br>
				<button type="submit" class="btn btn-info">Submit</button>
			</form>
			<p>{{ text }}</p>
			<ul>
			{% for post in posts %}
				<li>{{ post.post }}</li>
				<p>Posted by {{ post.user.get_full_name }} on {{ post.created }}
					{% if post.created.day < post.updated.day %}
						and updated on {{ post.updated }}
					{% endif %}
				</p>
			{% endfor %}
			</ul>
      		<br>
			
		</div>
		<div class="col-md-3">
			<h2>Other People</h2>			
			{% for user in users %}
				{% if user not in friends %}
				<a href="{% url 'accounts:view_profile_with_pk' pk=user.pk %}">
					<!--<img src="{{ user.userprofile.image.url }}" width="35" height="35">-->
					<h3>{{ user.username }}</h3>
				</a>
				<a href="{% url 'home:change_friend' operation='add' pk=user.pk %}">
					<button type="button" class="btn btn-success">Add Friend</button>
				</a>
				<br>
				<br>
				{% endif %}
			{% endfor %}
		</div>
		<div class="col-md-2">
			<h2>Friends</h2>
			{% for friend in friends %}
				<a href="{% url 'accounts:view_profile_with_pk' pk=friend.pk %}">
					<h3>{{ friend.username }}</h3>
				</a>
				<a href="{% url 'home:change_friend' operation='remove' pk=friend.pk %}">
					<button type="button" class="btn btn-danger">Remove Friend</button>
				</a>
			{% endfor %}
		</div>
	</div>
{% endblock %}