Tutorial/Tutorial/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from Tutorial import views as tutorial_views
from rest_framework import routers
from quickstart import views
from rest_framework.urlpatterns import format_suffix_patterns

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)
router.register(r'userprofile', views.UserProfileViewSet)

urlformatpatterns = [
#     path('snippets/', views.snippet_list),
#     path('snippets/<int:pk>/', views.snippet_detail),
    path('snippets/', views.SnippetList.as_view()),
    path('snippets/<int:pk>/', views.SnippetDetail.as_view()),
    path('users/', views.UserList.as_view()),
    path('users/<int:pk>/', views.UserDetail.as_view()),
]

urlformatpatterns = format_suffix_patterns(urlformatpatterns)

urlpatterns = [
    #path('',tutorial_views.login_redirect, name = 'login_redirect'),
	path('',tutorial_views.web_home, name = 'web_home'),
    path('admin/', admin.site.urls),
    path('drf/', include(router.urls)),
    path('account/', include(('accounts.urls', 'accounts'), namespace = 'accounts')),
    path('home/', include(('home.urls', 'home'), namespace = 'home')),
    path('paytm/', include(('paytm.urls', 'paytm'), namespace = 'paytm')),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + urlformatpatterns

Tutorial/home/urls.py
from django.urls import path, re_path
from home import views

# app_name = 'home'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    re_path(r'friend/(?P<operation>.+)/(?P<pk>\d+)/', views.change_friends, name='change_friend')
]

Tutorial/paytm/urls.py
from django.urls import path
from paytm import views

# app_name = 'paytm'

urlpatterns = [
    path('', views.response, name='home'),
    path('payment/', views.payment, name='payment'),
    path('response/', views.response, name='response'),
]

Tutorial/home/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    post = models.CharField(max_length=500)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    
class Friend(models.Model):
    users = models.ManyToManyField(User)
    current_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='owner', null=True)
    
    def __str__(self):
        return self.current_user.first_name.lower() + ' friends'
    
    @classmethod
    def make_friend(cls, current_user, new_friend):
        friend, created = cls.objects.get_or_create(current_user=current_user)
        friend.users.add(new_friend)
        
    @classmethod
    def lose_friend(cls, current_user, new_friend):
        friend, created = cls.objects.get_or_create(current_user=current_user)
        friend.users.remove(new_friend)

Tutorial/paytm/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class PaymentHistory(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='rel_payment_paytm')
    ORDERID = models.CharField('ORDER ID', max_length=30)
    TXNDATE = models.DateTimeField('TXN DATE', auto_now_add=True)
    TXNID = models.CharField('TXN ID', max_length=64)
    BANKTXNID = models.CharField('BANK TXN ID', max_length=20, null=True, blank=True)
    BANKNAME = models.CharField('BANK NAME', max_length=50, null=True, blank=True)
    RESPCODE = models.IntegerField('RESP CODE')
    PAYMENTMODE = models.CharField('PAYMENT MODE', max_length=10, null=True, blank=True)
    CURRENCY = models.CharField('CURRENCY', max_length=4, null=True, blank=True)
    GATEWAYNAME = models.CharField('GATEWAY NAME', max_length=30, null=True, blank=True)
    MID = models.CharField(max_length=40)
    RESPMSG = models.TextField('RESP MSG', max_length=250)
    TXNAMOUNT = models.FloatField('TXN AMOUNT')
    STATUS = models.CharField('STATUS', max_length=12)

    class Meta:
        app_label = 'paytm'

    def __unicode__(self):
        return self.STATUS

Tutorial/home/forms.py
from django import forms
from home.models import Post

class HomeForm(forms.ModelForm):
    post = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'form-control',
            'placeholder': 'Write a post...'
            }
        )
    )
    
    class Meta:
        model = Post
        fields = ('post',)

Tutorial/home/views.py
from django.views.generic import TemplateView
from django.shortcuts import render, redirect
from django.contrib.auth.models import User

from home.forms import HomeForm
from home.models import Post, Friend

import logging

class HomeView(TemplateView):
    template_name = 'home/home.html'
    
    def get(self, request):
        form = HomeForm()
        posts = Post.objects.all().order_by('-created')
        users = User.objects.exclude(id=request.user.id)
        
        friend, created = Friend.objects.get_or_create(current_user=request.user)
        friends = friend.users.all()
            
        args = {'form': form, 'posts': posts, 'users': users, 'friends': friends}
        return render(request, self.template_name, args)
    
    def post(self, request):
        form = HomeForm(request.POST)
        
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            
            text = form.cleaned_data['post']
            form = HomeForm()
            return redirect('home:home')
            
        args = {'form': form, 'text': text}
        return render(request, self.template_name, args)
    
def change_friends(request, operation, pk):
    friend = User.objects.get(pk=pk)
    if operation == 'add':
        Friend.make_friend(request.user, friend)
    elif operation == 'remove':
        Friend.lose_friend(request.user, friend)
        
    return redirect('home:home')

Tutorial/paytm/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from django.conf import settings
from paytm import checksum
from paytm.models import PaymentHistory
# Create your views here.

@login_required
def payment(request):
    CALLBACK_URL = settings.HOST_URL + settings.PAYTM_CALLBACK_URL
    # Generating unique temporary ids
    order_id = checksum.__id_generator__()

    bill_amount = request.POST['amount']
    if bill_amount:
        data_dict = {
                    'MID':settings.PAYTM_MERCHANT_ID,
                    'ORDER_ID':order_id,
                    'TXN_AMOUNT': bill_amount,
                    'CUST_ID':request.user.email,
                    'INDUSTRY_TYPE_ID':settings.PAYTM_INDUSTRY_TYPE,
                    'WEBSITE': settings.PAYTM_WEBSITE,
                    'CHANNEL_ID':'WEB',
                    'CALLBACK_URL':CALLBACK_URL,
                }
        param_dict = data_dict
        param_dict['CHECKSUMHASH'] = checksum.generate_checksum(data_dict, settings.PAYTM_MERCHANT_KEY)
        return render(request,"paytm/payment.html",{'paytmdict':param_dict})
    return HttpResponse("Bill Amount Could not find. ?bill_amount=10")

@login_required
@csrf_exempt
def response(request):
    if request.method == 'GET':
        return render(request, 'paytm/home.html')
    elif request.method == "POST":
        data_dict = {}
        for key in request.POST:
            data_dict[key] = request.POST[key]
        verify = checksum.verify_checksum(data_dict, settings.PAYTM_MERCHANT_KEY, data_dict['CHECKSUMHASH'])
        if verify:
            for key in request.POST:
                if key == "BANKTXNID" or key == "RESPCODE":
                    if request.POST[key]:
                        data_dict[key] = int(request.POST[key])
                    else:
                        data_dict[key] = 0
                elif key == "TXNAMOUNT":
                    data_dict[key] = float(request.POST[key])
            PaymentHistory.objects.create(user=request.user, **data_dict)
            return render(request,"paytm/response.html",{"paytm":data_dict})
        else:
            return HttpResponse("checksum verify failed")
    return HttpResponse(status=200)

Tutorial/paytm/templates/paytm/home.html
{% extends 'base.html' %}

{% block head %}
	<title>Merchant Check Out Page</title>
{% endblock %}

{% block body %}
	<div class="container">
		<h3>Rajkumar Technologies Pvt Ltd.</h3>
		<br>
		<form method="post" align='center' action="{% url 'paytm:payment' %}">
			{% csrf_token %}
			<input type="number" name="amount" min="1" max="50000">
			<br>
			<br>
			<button type="submit" class="btn btn-primary">Proceed to pay</button>
		</form>
		<br>
		<a class="btn btn-secondary" href="{% url 'home:home' %}" role="button">Back</a>
	</div>
	<form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
		<input type="hidden" name="cmd" value="_s-xclick">
		<input type="hidden" name="hosted_button_id" value="Z4Y52DLF7PXXN">
		<input type="image" src="https://www.paypalobjects.com/en_GB/i/btn/btn_buynowCC_LG.gif" border="0" name="submit" alt="PayPal – The safer, easier way to pay online!">
		<img alt="" border="0" src="https://www.paypalobjects.com/en_GB/i/scr/pixel.gif" width="1" height="1">
	</form>

{% endblock %}

Tutorial/paytm/templates/paytm/payment.html
{% extends 'base.html' %}

{% block head %}
	<title>Paytm Secure Online Payment Gateway</title>
{% endblock %}

{% block body %}
       <table align='center'>
           <tr><td><STRONG>Transaction is being processed,</STRONG></td></tr>
           <tr><td><font color='blue'>Please wait ...</font></td></tr>
           <tr><td>(Please do not press 'Refresh' or 'Back' button)</td></tr>
       </table>
	   <!--<form method="post" action="https://securegw.paytm.in/theia/processTransaction" name="f1">-->
       <form method="post" action="https://securegw-stage.paytm.in/theia/processTransaction" name="f1">
       <table border="1">
           <tbody>
           {% for key,value in paytmdict.items %}
               <input type="hidden" name="{{key}}" value="{{value}}">
           {% endfor %}
           </tbody>
       </table>
       <script type="text/javascript">
           document.f1.submit();
       </script>
       </form>
{% endblock %}

Tutorial/paytm/templates/paytm/response.html
{% extends 'base.html' %}

{% block head %}
	<title>Transaction Status</title>
{% endblock %}

{% block body %}
	<div class="container">
		<h3>Rajkumar Technologies Pvt Ltd.</h3>
		<br>
		<h4>Transaction completed</h4>
		<br>
		<p>Below are the transaction details</p>
		<br>
		{% for key,value in paytm.items %}
		    {{key}} =  {{value}} <br>
		{% endfor %}
		<br>
		<a class="btn btn-secondary" href="{% url 'home:home' %}" role="button">Back</a>
	</div>
{% endblock %}